[package]
name = "peace_sol_canvas"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-program = "1.10.32"  # Adjust the version as needed
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"